
export const metadata = {
    title: 'View Detail Blog',
    description: 'Generated by Minh SEN',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <>
          {children}
      </>
    )
  }
  